#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Ensure the correct permissions for the web root directory
sudo chown -R ubuntu:ubuntu /var/www/html

# Create a custom index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom 404 page
echo - e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html

# Get the hostname of the server
hostname=$(hostname)

# Variables for new configuration parts
custom_header="\n\tadd_header X-Served-By $hostname;"
redirect_location="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
error_page_config="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"

# Insert custom configurations into the Nginx default site configuration
sudo sed -i "/server_name _;/a \\t$custom_header$redirect_location$error_page_config" /etc/nginx/sites-available/default

# Check Nginx configuration syntax
sudo nginx -t

# Restart and reload Nginx to apply the changes
sudo service nginx restart
sudo service nginx reload
