#!/usr/bin/env bash
# Script that configures a load balancer for Ubuntu 23.10
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\
frontend http
bind *:80
mode http
default_backend web-server
backend web-server
balance roundrobin
server 224789-web-01    52.23.178.121:80 check
server 224789-web-02 54.172.161.127:80 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
