#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal
# script that basically runs forever

file="/var/run/holbertonscript.pid"
pid=$$

echo $pid | cat > $file

sigterm() {
	echo "I hate the kill command"
	sudo rm $file
	kill -9 $pid
}

sigint() {
	echo "Y U no love me?!"
}

quit() {
	sudo rm $file
	kill -9 $pid
}

trap sigterm SIGTERM
trap sigint  SIGINT
trap quit    SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
